#!/command/with-contenv bash
# Purpose: Configures SMTP messaging settings for the container
# These defaults can be overridden by setting the environment variables externally

set -euo pipefail
IFS=$'\n\t'

#--------------------------------------------------
# Configuration
#--------------------------------------------------
# SMTP server settings
SMTP_HOST=${SMTP_HOST:-"postfix-relay"}
SMTP_PORT=${SMTP_PORT:-"25"}
SMTP_DOMAIN=${SMTP_DOMAIN:-"docker"}
SMTP_MAILDOMAIN=${SMTP_MAILDOMAIN:-"local"}
SMTP_AUTO_FROM=${SMTP_AUTO_FROM:-"FALSE"}

# SMTP security settings
SMTP_TLS=${SMTP_TLS:-"FALSE"}
SMTP_STARTTLS=${SMTP_STARTTLS:-"FALSE"}
SMTP_TLSCERTCHECK=${SMTP_TLSCERTCHECK:-"FALSE"}
