#!/command/with-contenv bash

# Source the main container functions
source /assets/functions/00-container

# Disable verbose output for cleaner logs
output_off

# Prepare single service startup
prepare_service

# Define process name for logging
PROCESS_NAME="logging"

# Check if log rotation is enabled in the container
if var_true "${CONTAINER_ENABLE_LOGROTATE}" ; then
    # Log a message indicating that log rotation is enabled
    print_debug "Enabling log rotation"

    # Determine the log compression method based on the configuration
    case "${LOGROTATE_COMPRESSION_TYPE,,}" in
        bz* )
            # Configure bzip2 compression for log rotation
            logrotate_compression=$(cat <<EOF
compress
compresscmd $(which bzip2)
compressext .bz2
compressoptions -${LOGROTATE_COMPRESSION_VALUE} ${LOGROTATE_COMPRESSION_EXTRA_PARAMETERS}
EOF
            )
        ;;
        gz* )
            # Configure gzip compression for log rotation
            logrotate_compression=$(cat <<EOF
compress
compresscmd $(which gzip)
compressext .gz
compressoptions -${LOGROTATE_COMPRESSION_VALUE} ${LOGROTATE_COMPRESSION_EXTRA_PARAMETERS}
EOF
            )
        ;;
        none )
            # Disable compression for log rotation
            logrotate_compression=""
        ;;
        zs* )
            # Configure zstd compression for log rotation
            logrotate_compression=$(cat <<EOF
compress
compresscmd $(which zstd)
compressext .zst
compressoptions -${LOGROTATE_COMPRESSION_VALUE} ${LOGROTATE_COMPRESSION_EXTRA_PARAMETERS}
EOF
            )
        ;;
    esac

    # Create the main logrotate configuration file
    cat <<EOF > /etc/logrotate.conf
daily
rotate ${LOGROTATE_RETAIN_DAYS}
copytruncate
dateext
nomail
notifempty
${logrotate_compression}
include /etc/logrotate.d
EOF

    # Set appropriate permissions for the logrotate configuration
    chmod 0744 /etc/logrotate.conf

    # Prepare the container's scheduling location for log rotation tasks
    mkdir -p "${CONTAINER_SCHEDULING_LOCATION}"

    # Add a cron job for daily log rotation
    cat <<EOF > "${CONTAINER_SCHEDULING_LOCATION}"/logrotate
# Scheduled log rotation job
# Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

59 23 * * * logrotate -f /etc/logrotate.conf >/dev/null 2>&1
EOF
fi

# Check if log shipping is disabled
if var_false "${CONTAINER_ENABLE_LOGSHIPPING}" ; then
    service_stop "$(basename "$0")"
else
    # Determine the logging backend to use
    case "${CONTAINER_LOGSHIPPING_BACKEND,,}" in
        "fluent-bit" | "fluentbit" )
            # Detect the operating system
            os=$(grep ^ID= /etc/os-release | cut -d= -f2)

            # Check OS-specific requirements
            case ${os,,} in
                "alpine" )
                    # Detect system architecture on Alpine Linux
                    archit=$(apk --print-arch)

                    # Verify architecture compatibility
                    case "$archit" in
                        x86_64)
                            # Verify Alpine version compatibility (>= 3.11)
                            osver=$(cat /etc/os-release | grep VERSION_ID | cut -d = -f 2 | cut -d . -f 2 | cut -d _ -f 1)
                            if [ "${osver}" -ge 11 ] || [ "$osver" = "edge" ] || [ "$osver" = "17*" ]; then
                                :
                            else
                                print_error "Sorry this functionality is not available on < Alpine 3.11 releases"
                                service_stop "$(basename "$0")"
                                liftoff
                                exit 0
                            fi
                        ;;
                        *)
                            # Exit if architecture is not supported
                            print_error "This functionality is not available on the '${archit}' architecture"
                            service_stop "$(basename "$0")"
                            liftoff
                            exit
                        ;;
                    esac
                ;;
                "debian" | "ubuntu" )
                    # Detect system architecture on Debian or Ubuntu
                    archit=$(dpkg --print-architecture)

                    # Verify architecture compatibility
                    case "$archit" in
                        amd64)
                            # Supported architecture, no action required
                            :
                        ;;
                        *)
                            # Exit if architecture is not supported
                            print_error "This functionality is not available on the '${archit}' architecture"
                            service_stop "$(basename "$0")"
                            liftoff
                            exit
                        ;;
                    esac
                ;;
            esac

            # Auto-configure Fluent-bit if enabled
            if [ "${FLUENTBIT_SETUP_TYPE,,}" = "auto" ] ; then
                # Log the initialization of Fluent-bit agent configuration
                print_debug "[logship] Configuring Fluent-bit agent"

                # Convert true/false to on/off for Fluent-bit settings
                truefalse_onoff FLUENTBIT_ENABLE_HTTP_SERVER
                truefalse_onoff FLUENTBIT_ENABLE_STORAGE_METRICS
                truefalse_onoff FLUENTBIT_STORAGE_CHECKSUM

                # Create necessary directories for Fluent-bit
                mkdir -p "${FLUENTBIT_STORAGE_PATH}"
                mkdir -p "${FLUENTBIT_LOG_PATH}"
                mkdir -p /etc/fluent-bit/conf.d

                # Generate a mandatory Fluent-bit configuration file
                cat <<EOF > /etc/fluent-bit/conf.d/do_not_delete.conf
# Mandatory configuration file for Fluent-bit
# This file ensures the Fluent-bit agent doesn't fail if no other configurations are present
[INPUT]
    Name   dummy
    Tag    ignore

[FILTER]
    Name grep
    Match ignore
    Regex ignore ignore

[OUTPUT]
    Name   NULL
    Match  ignore
EOF

                # Check for additional parser configurations in the parsers directory
                if [ "$(ls -A /etc/fluent-bit/parsers.d/)" ]; then
                    # Enable nullglob to handle empty directories gracefully
                    shopt -s nullglob
                    for custom_parser in /etc/fluent-bit/parsers.d/*.conf ; do
                        # Log the detection of additional parsers
                        print_debug "[logship] Found additional parser: '$(basename "${custom_parser,,}" .conf)'"

                        # Append parser files to the additional parsers configuration
                        additional_parsers=$(echo "${additional_parsers}" ; cat<<EOF
    parsers_file ${custom_parser}
EOF
                        )
                    done
                    # Disable nullglob after processing
                    shopt -u nullglob
                fi

                # Generate the main Fluent-bit configuration file
                cat <<EOF > /etc/fluent-bit/fluent-bit.conf
## Auto-generated Fluent-bit configuration
## Generated on $(TZ=${TIMEZONE} date +'%Y-%m-%d %H:%M:%S %Z')

# Include all configuration files from the conf.d directory
@INCLUDE conf.d/*.conf

[SERVICE]
    # Run Fluent-bit as a foreground process (disable daemon mode)
    daemon       Off

    # Frequency of data flushing (in seconds)
    flush        ${FLUENTBIT_FLUSH_SECONDS}

    # Grace period for shutdown (in seconds)
    grace        ${FLUENTBIT_GRACE_SECONDS}

    # HTTP Server Configuration for Monitoring and Metrics
    http_listen  ${FLUENTBIT_HTTP_LISTEN_IP}
    http_port    ${FLUENTBIT_HTTP_LISTEN_PORT}
    http_server  ${FLUENTBIT_ENABLE_HTTP_SERVER}

    # Logging Configuration
    log_file     ${FLUENTBIT_LOG_PATH}/${FLUENTBIT_LOG_FILE}
    log_level    ${FLUENTBIT_LOG_LEVEL}

    # Plugin Configuration
    plugins_file ${FLUENTBIT_CONFIG_PLUGINS}

    # Storage Configuration
    storage.backlog.mem_limit ${FLUENTBIT_STORAGE_BACKLOG_LIMIT} # Memory limit for the storage backlog
    storage.checksum ${FLUENTBIT_STORAGE_CHECKSUM}               # Enable or disable checksum validation
    storage.metrics ${FLUENTBIT_ENABLE_STORAGE_METRICS}          # Enable or disable storage metrics
    storage.path ${FLUENTBIT_STORAGE_PATH}                       # Path for storing temporary files
    storage.sync ${FLUENTBIT_STORAGE_SYNC}                       # Synchronization method for storage

    # Parser Configuration
    parsers_file ${FLUENTBIT_CONFIG_PARSERS}                     # Default parser file
${additional_parsers}                                            # Additional parser files included dynamically
EOF
