---
name: Bug Report
about: Report a reproducible bug with this container image
title: "[Bug] "
labels: [bug]
assignees: []
---

## Description
A clear and concise description of what the issue is.

## Steps to Reproduce
1. Pull image with `docker pull focela/debian:<tag>`
2. Run container with `docker run -e VARIABLE=value ...`
3. Run command `...` inside container
4. Observe error `...`

## Expected Behavior
What should have happened?

## Actual Behavior
What actually happened? Include logs or screenshots if applicable.

## Environment
- **Image version**: e.g. `7.10.31`
- **Container platform**: e.g. Docker, Podman, Kubernetes
- **Architecture**: e.g. amd64, arm64, armv7
- **Host OS**: e.g. Ubuntu 22.04
- **Docker version**: e.g. Docker 24.0.5

## Configuration
```yaml
# Provide your docker-compose.yml or relevant environment variables
```

## Additional Context
Add any other context about the problem here.
